### ISSUE TITLE
Private keys are not secured 

### ISSUE THREAD

**Issue by Benjamin-Pasternak** [henrychu04/CS419-Computer-Security-Project#2]
We are able to just look at all private keys by going to the directory they are stored and opening the perm files. This means that if a bad actor has access to these perm files, they have access to all chat messages sent.

**Comment by henrychu04** [comment]
The private keys are accessible in the repo for preset data purposes with already existing users.

If a client were to register a new user, then the generated private key would only be stored on the client's computer and it will never be sent to the server nor can the server access the private keys. If a bad actor has access to the user's private keys stored on their own computer, then that means the client has bigger issues to worry about. In other words, a bad actor will only be able to access the pem files if they have access to the client's entire computer.

This is all under the assumption that the server is hosted on a cloud service and that different client computers were to connect to it, but I didn't think it was necessary to host the server on a cloud service because this is just a school project. So for now, the pem files are here in the repo for preset data purposes only.

Anyways this doesn't even matter, because if you are running the program on only your own computer, you are able to access every user's pem file. This design was designed with the intent for the server to be hosted on it's own computer and the clients ran on separate computers.

**Comment by symxmyz233** [comment]
**it is not a bug.**
