### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by Ling2000** [henrychu04/CS419-Computer-Security-Project#3]
It seems like two windows can log into the same account simultaneously. It may cause some security problems.

**Comment by henrychu04** [comment]
I did not not limit the number of logged in sessions per user because for any major messaging platform, like Facebook Messenger or Signal, anyone can login to the same account as many times as they want as long as they have the password. If a user’s password has been obtained by a third party somehow, then the third party did not obtain it through the use of the app, because the app sends and stores the encrypted version of the password, which a third party cannot decrypt in a reasonable way.

**Comment by Ling2000** [comment]
Now, for most apps, only having a user name and password is not enough. The website will also send verification to the email or message. That is because only the user name and password combination are not saved enough. That is not important. I see you use RSA package. Are we really allowed to use a scheme that finishes by the other?

**Comment by symxmyz233** [comment]
Using RSA package is allowed. This issue **is not a bug.**
